name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t simple-webapp:1.0 .

    - name: Deploy to DigitalOcean
      env:
        DOCKER_HOST: tcp://${{ secrets.DOCKER_HOST }}:80
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker stop simple-webapp:1.0 || true
        docker rm simple-webapp:1.0 || true
        docker run -d -p 80:8080 --name simple-webapp:1.0 simple-webapp:1.0
